# Generated by Django 4.2.16 on 2026-07-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='meeting',
            name='uniq_organizer_slot',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REQUESTED', 'Requested'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'REQUESTED', 'CONFIRMED'])), fields=('organizer', 'start_at'), name='uniq_organizer_slot'),
        ),
    ]
