# Generated by Django 4.2.16 on 2026-07-14 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_meeting_uniq_organizer_slot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'start_time'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='meeting',
            name='uniq_organizer_slot',
        ),
        migrations.AddField(
            model_name='meeting',
            name='booking_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='tool_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='meetingattendee',
            name='type',
            field=models.CharField(choices=[('DEVELOPER', 'Developer'), ('SCRUM_MASTER', 'Scrum Master'), ('CC', 'Cc'), ('REQUIRED', 'Required')], default='REQUIRED', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='dailyslot',
            unique_together={('start_time', 'end_time')},
        ),
        migrations.AddField(
            model_name='meeting',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scheduler.dailyslot'),
        ),
    ]
