# Generated by Django 4.2.16 on 2026-07-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_dailyslot_remove_meeting_uniq_organizer_slot_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'REQUESTED', 'CONFIRMED'])), fields=('tool_key', 'booking_date', 'slot'), name='uniq_tool_date_slot'),
        ),
    ]
