# Generated by Django 4.2.16 on 2026-09-14 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0005_meeting_cancellation_reason_meeting_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='escalation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='go_live_done',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='go_live_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='go_live_done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='golive_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
