# Generated by Django 4.2.16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminconfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtemplate',
            name='key',
            field=models.SlugField(max_length=32),
        ),
        migrations.AddField(
            model_name='meetingtemplate',
            name='tool',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='meeting_templates',
                to='adminconfig.toolconfig',
                help_text='Leave blank for the global fallback template.',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='meetingtemplate',
            unique_together={('key', 'tool')},
        ),
    ]
