# Generated by Django 4.2.16 on 2026-09-14 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminconfig', '0003_automationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default escalation policy', max_length=64)),
                ('manager_emails', models.TextField(blank=True, default='', help_text='Comma-separated manager/escalation recipients. Example: delivery-manager@ericsson.com')),
                ('escalation_day', models.PositiveSmallIntegerField(default=15, help_text='Days after the handover date to escalate to managers if the JIRA is still not GO-live. Default 15.')),
                ('cc_team', models.BooleanField(default=True, help_text='Also CC the per-tool team + organizer on the escalation email.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Escalation policy (global)',
                'verbose_name_plural': 'Escalation policy (global)',
            },
        ),
        migrations.CreateModel(
            name='HandoverFollowupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_emails', models.TextField(blank=True, default='', help_text='Comma-separated team recipients for the GO-live reminder. Example: team-lead@ericsson.com, squad@ericsson.com')),
                ('go_live_day', models.PositiveSmallIntegerField(default=10, help_text="Days after the handover date to send the 'move JIRA to GO live' reminder to the team. Default 10.")),
                ('is_active', models.BooleanField(default=True)),
                ('tool', models.OneToOneField(help_text='The automation tool this follow-up rule applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='followup_config', to='adminconfig.toolconfig')),
            ],
            options={
                'verbose_name': 'Handover follow-up config (per tool)',
                'verbose_name_plural': 'Handover follow-up configs (per tool)',
                'ordering': ['tool__sort_order', 'tool__key'],
            },
        ),
    ]
