# Generated by Django 4.2.16 on 2026-09-20 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminconfig', '0004_escalationpolicy_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetingtemplate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='automationtype',
            name='notification_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of email addresses to CC on every scan completion notification for this type. Example: manager@ericsson.com, team-lead@ericsson.com'),
        ),
        migrations.AlterField(
            model_name='meetingtemplate',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_templates', to='adminconfig.toolconfig'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingtemplate',
            unique_together={('tool', 'key')},
        ),
    ]
