# Generated by Django 4.2.16 on 2026-09-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminconfig', '0005_alter_meetingtemplate_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=64)),
                ('requires_parent', models.BooleanField(default=False, help_text='If true, selecting this type reveals the Enhancement JIRA ID field and treats the main JIRA as the Parent JIRA.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'JIRA type',
                'verbose_name_plural': 'JIRA types',
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.AddField(
            model_name='toolconfig',
            name='eridoc_path_mode',
            field=models.CharField(choices=[('REQUIRED', 'Required'), ('OPTIONAL', 'Optional')], default='OPTIONAL', help_text='ERIDOC folder path on Verify: REQUIRED = must be entered; OPTIONAL = blank falls back to original JIRA-based lookup.', max_length=8),
        ),
    ]
