# Generated by Django 4.2.16 on 2026-09-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminconfig', '0006_jiratype_toolconfig_eridoc_path_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EscalationPolicy',
        ),
        migrations.AlterModelOptions(
            name='jiratype',
            options={'ordering': ['sort_order', 'key'], 'verbose_name': 'JIRA Type', 'verbose_name_plural': 'JIRA Types'},
        ),
        migrations.AlterField(
            model_name='automationtype',
            name='requires_scheduling',
            field=models.BooleanField(default=True, help_text='Tick = Execution flow (scan -> schedule meeting). Untick = Document-only flow (scan -> email report, no meeting).'),
        ),
        migrations.AlterField(
            model_name='jiratype',
            name='key',
            field=models.SlugField(help_text='Short identifier, e.g. STORY or ENHANCEMENT', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='jiratype',
            name='requires_parent',
            field=models.BooleanField(default=False, help_text='Tick for Enhancement-style types: the main JIRA field becomes the Parent JIRA and a separate Enhancement JIRA ID is required.'),
        ),
        migrations.AlterField(
            model_name='meetingtemplate',
            name='subject_pattern',
            field=models.CharField(default='Release Review - {jira_id}', max_length=200),
        ),
        migrations.AlterField(
            model_name='toolconfig',
            name='eridoc_path_mode',
            field=models.CharField(choices=[('REQUIRED', 'Required - user must enter an ERIDOC folder path'), ('OPTIONAL', 'Optional - blank falls back to the JIRA-based lookup')], default='OPTIONAL', help_text="Controls the ERIDOC folder-path field on the Verify page. Only relevant when this tool's scanners include ERIDOC. REQUIRED = the field must be filled; OPTIONAL = blank falls back to the original JIRA-based ERIDOC lookup.", max_length=8),
        ),
        migrations.DeleteModel(
            name='HandoverFollowupConfig',
        ),
    ]
