# Generated by Django 4.2.16 on 2026-07-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', through='rbac.UserRole', to='rbac.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SCRUM_MASTER', 'Scrum Master'), ('VIEWER', 'Viewer')], default='SCRUM_MASTER', help_text='Legacy display label; real permissions come from `roles`.', max_length=20),
        ),
    ]
