# Generated by Django 4.2.16 on 2026-07-10 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminconfig', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jira_id', models.CharField(db_index=True, max_length=32)),
                ('repo_url', models.URLField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('ERROR', 'Error')], default='PENDING', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(default=dict)),
                ('pdf_file', models.FileField(blank=True, default='', upload_to='reports/')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminconfig.toolconfig')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanner', models.CharField(max_length=16)),
                ('status', models.CharField(default='PENDING', max_length=10)),
                ('passed_checks', models.JSONField(default=list)),
                ('failed_checks', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('missing_documents', models.JSONField(default=list)),
                ('blank_documents', models.JSONField(default=list)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='validation.validationrun')),
            ],
            options={
                'unique_together': {('run', 'scanner')},
            },
        ),
        migrations.CreateModel(
            name='ScannerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='validation.validationresult')),
            ],
        ),
    ]
