# Generated by Django 4.2.16 on 2026-07-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationresult',
            name='stats',
            field=models.JSONField(default=dict),
        ),
    ]
