# Generated by Django 4.2.16 on 2026-07-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0002_validationresult_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
