# Generated by Django 4.2.16 on 2026-07-16 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('validation', '0003_validationrun_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationresult',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('ERROR', 'Error'), ('CANCELLING', 'Cancelling'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
    ]
