# Generated by Django 4.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0004_validationresult_celery_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='automation_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
