# Generated by Django 4.2.16 on 2026-09-20 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminconfig', '0007_delete_escalationpolicy_alter_jiratype_options_and_more'),
        ('validation', '0006_validationrun_automation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='enhancement_jira_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='eridoc_path',
            field=models.CharField(blank=True, default='', help_text='Explicit ERIDOC folder path/link. When blank the scanner falls back to the JIRA-based lookup.', max_length=512),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='jira_type',
            field=models.ForeignKey(blank=True, help_text='Story or Enhancement (configurable in admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_runs', to='adminconfig.jiratype'),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='parent_jira_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
