# Generated by Django 4.2.16 on 2026-07-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='action',
            field=models.CharField(blank=True, db_index=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='module',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='method',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='path',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
